gpu_model: "NVIDIA GeForce RTX 4070"
benchmarks:
  hpcdl:
    enabled: true
    iterations: 3
    description: "Training a dummy neural network to benchmark GPU performance."
  gaming:
    enabled: true
    iterations: 3
    description: "Simulated gaming benchmark workload."
  stress:
    enabled: true
    iterations: 1
    description: "GPU stress test with heavy matrix multiplications."
